spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: ${SERVER_PORT:8080}
security:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
totp:
  secret: ${TOTP_SECRET}
jwt:
  secret: ${JWT_SECRET}
  otpExpirationMinutes: 5
  authExpirationMinutes: 60
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
